### ISSUE TITLE
Big files can cause big issues

### ISSUE THREAD

**Issue by Darkhax** [Diluv/Catalejo#2]
Gegy reported an issue in [this](https://github.com/Diluv/Catalejo/blob/development/src/main/java/com/diluv/catalejo/reader/files/FileSizeReader.java#L40) code. If a file is big enough it can throw an exception here. Better error handling should be added to make this method safer.

**Comment by lclc98** [comment]
https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/FileUtils.html#byteCountToDisplaySize(long) Has support for it if we want to add that lib. It is safe from what I see

**Comment by Darkhax** [comment]
Their code is likely the same as current. This is an easy fix, no need to bring in a lib.
